config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :patients

  resources :notes do
  member do
    get "vote"
  end
end

  resources :charges

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :patient
  belongs_to :user
  has_one :charge
  acts_as_votable 
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy, :vote]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  #->Prelang (voting/acts_as_votable)
  def vote

    direction = params[:direction]

    # Make sure we've specified a direction
    raise "No direction parameter specified to #vote action." unless direction

    # Make sure the direction is valid
    unless ["like", "bad"].member? direction
      raise "Direction '#{direction}' is not a valid direction for vote method."
    end

    @note.vote_by voter: current_user, vote: direction

    redirect_to action: :index
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:patient_id, :user_id, :primary_author, :primary_institution, :body_text, :ocr, :type, :title, :filing_date)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<%= form_for @note, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :primary_author, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :primary_author, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :primary_institution, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :primary_institution, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body_text, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :body_text, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :ocr, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :ocr, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :type, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :type, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :filing_date, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :filing_date, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  notes_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/notes/edit.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Note %></h1>
</div>
<%= render :partial => 'form' %>

app/views/notes/index.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => Note %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:primary_author) %></th>
      <th><%= model_class.human_attribute_name(:primary_institution) %></th>
      <th><%= model_class.human_attribute_name(:body_text) %></th>
      <th><%= model_class.human_attribute_name(:ocr) %></th>
      <th><%= model_class.human_attribute_name(:type) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:filing_date) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.id %></td>
        <td><%= note.primary_author %></td>
        <td><%= note.primary_institution %></td>
        <td><%= note.body_text %></td>
        <td><%= note.ocr %></td>
        <td><%= note.type %></td>
        <td><%= note.title %></td>
        <td><%= note.filing_date %></td>
        <td><%=l note.created_at, format: :long %></td>
        <td>
          <%= link_to note_path(note), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to note_path(note), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_note_path,
            :class => 'btn btn-primary' %>

app/views/notes/new.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Note %></h1>
</div>
<%= render :partial => 'form' %>

app/views/notes/show.html.erb
<%- model_class = Note -%>
<div class="page-header">
  <h1><%=t '.title', :default => Note %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:primary_author) %></dt>
      <dd><pre class="prettyprint"><%= @note.primary_author %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:primary_institution) %></dt>
      <dd><pre class="prettyprint"><%= @note.primary_institution %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:body_text) %></dt>
      <dd><pre class="prettyprint"><%= @note.body_text %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:ocr) %></dt>
      <dd><pre class="prettyprint"><%= @note.ocr %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:type) %></dt>
      <dd><pre class="prettyprint"><%= @note.type %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:title) %></dt>
      <dd><pre class="prettyprint"><%= @note.title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:filing_date) %></dt>
      <dd><pre class="prettyprint"><%= @note.filing_date %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              notes_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_note_path(@note), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              note_path(@note),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>